/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas.Trabajador;

import Entidades.Mensaje;
import static Main.ServicioDeAgua.mensaje;
import Utilidades.ServiciosUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hansel Chavez
 */
public class pnlComentarios extends javax.swing.JPanel {

    /**
     * Creates new form pnlComentariosSolicitante
     */
  
    List<Mensaje> listaRetro ;
    ServiciosUsuario servicio;
    String tipo;
    int cod;   
    public pnlComentarios() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSliderRetro = new rojerusan.RSPanelEffect();
        pnlTablaRetro = new javax.swing.JPanel();
        txtBuscarComentario = new RSMaterialComponent.RSTextFieldMaterialIcon();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaComentarios = new RSMaterialComponent.RSTableMetroCustom();
        btnSugerencias = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnReclamos = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnVisualizarRetro = new RSMaterialComponent.RSButtonMaterialIconOne();
        pnlVisualizar = new javax.swing.JPanel();
        lblestado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcontenido = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        lblIDRetro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        btnVolver = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlSliderRetro.setBackground(new java.awt.Color(255, 255, 255));

        pnlTablaRetro.setBackground(new java.awt.Color(255, 255, 255));
        pnlTablaRetro.setName("pnlTablaRetro"); // NOI18N

        txtBuscarComentario.setForeground(new java.awt.Color(0, 108, 255));
        txtBuscarComentario.setColorIcon(new java.awt.Color(0, 108, 255));
        txtBuscarComentario.setColorMaterial(new java.awt.Color(0, 108, 255));
        txtBuscarComentario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscarComentario.setPhColor(new java.awt.Color(0, 69, 255));
        txtBuscarComentario.setPlaceholder("Buscar");
        txtBuscarComentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarComentarioKeyReleased(evt);
            }
        });

        jScrollPane3.setBorder(null);

        tablaComentarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Mensaje", "ID Usuario", "Contenido", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaComentarios.setBackgoundHead(new java.awt.Color(0, 108, 255));
        tablaComentarios.setBackgoundHover(new java.awt.Color(10, 94, 208));
        tablaComentarios.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaComentarios.setColorSecondary(new java.awt.Color(255, 255, 255));
        tablaComentarios.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaComentarios.setRowHeight(40);
        tablaComentarios.setSelectionBackground(new java.awt.Color(78, 85, 230));
        jScrollPane3.setViewportView(tablaComentarios);
        if (tablaComentarios.getColumnModel().getColumnCount() > 0) {
            tablaComentarios.getColumnModel().getColumn(2).setPreferredWidth(400);
            tablaComentarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        btnSugerencias.setBackground(new java.awt.Color(204, 204, 204));
        btnSugerencias.setText("Sugerencias");
        btnSugerencias.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnSugerencias.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnSugerencias.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnSugerencias.setForegroundText(new java.awt.Color(0, 0, 0));
        btnSugerencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSugerencias.setIconTextGap(29);
        btnSugerencias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSISTANT);
        btnSugerencias.setPaddingLeft(15);
        btnSugerencias.setSelected(true);
        btnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugerenciasActionPerformed(evt);
            }
        });

        btnReclamos.setBackground(new java.awt.Color(204, 204, 204));
        btnReclamos.setText("Reclamos");
        btnReclamos.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnReclamos.setForegroundIcon(new java.awt.Color(204, 0, 0));
        btnReclamos.setForegroundText(new java.awt.Color(204, 0, 0));
        btnReclamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReclamos.setIconTextGap(29);
        btnReclamos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ANNOUNCEMENT);
        btnReclamos.setPaddingLeft(15);
        btnReclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamosActionPerformed(evt);
            }
        });

        btnVisualizarRetro.setBackground(new java.awt.Color(204, 204, 204));
        btnVisualizarRetro.setText("Ver Comentario");
        btnVisualizarRetro.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnVisualizarRetro.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVisualizarRetro.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVisualizarRetro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVisualizarRetro.setIconTextGap(29);
        btnVisualizarRetro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY);
        btnVisualizarRetro.setPaddingLeft(15);
        btnVisualizarRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarRetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaRetroLayout = new javax.swing.GroupLayout(pnlTablaRetro);
        pnlTablaRetro.setLayout(pnlTablaRetroLayout);
        pnlTablaRetroLayout.setHorizontalGroup(
            pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                        .addComponent(btnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(txtBuscarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVisualizarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        pnlTablaRetroLayout.setVerticalGroup(
            pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(btnVisualizarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        pnlSliderRetro.add(pnlTablaRetro, "card3");

        pnlVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        pnlVisualizar.setName("pnlVisualizar"); // NOI18N

        lblestado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblestado.setText("Visualizar Comentario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 45, 223));
        jLabel4.setText("Comentario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 45, 223));
        jLabel2.setText("Fecha :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 45, 223));
        jLabel3.setText("ID Comentario: ");

        txtcontenido.setColumns(20);
        txtcontenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcontenido.setLineWrap(true);
        txtcontenido.setRows(5);
        txtcontenido.setWrapStyleWord(true);
        txtcontenido.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtcontenido.setCaretColor(new java.awt.Color(153, 153, 153));
        txtcontenido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtcontenido.setEnabled(false);
        txtcontenido.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(txtcontenido);

        lblFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblIDRetro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 45, 223));
        jLabel5.setText("Tipo: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 45, 223));
        jLabel6.setText("ID Usuario:");

        lblTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblIdUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlVisualizarLayout = new javax.swing.GroupLayout(pnlVisualizar);
        pnlVisualizar.setLayout(pnlVisualizarLayout);
        pnlVisualizarLayout.setHorizontalGroup(
            pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisualizarLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizarLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(pnlVisualizarLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizarLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(lblIDRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)
                                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90))
        );
        pnlVisualizarLayout.setVerticalGroup(
            pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblestado)
                .addGap(30, 30, 30)
                .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlSliderRetro.add(pnlVisualizar, "card2");

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setText("Volver");
        btnVolver.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnVolver.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVolver.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setIconTextGap(29);
        btnVolver.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_ARROW_LEFT);
        btnVolver.setPaddingLeft(15);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSliderRetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSliderRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarComentarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarComentarioKeyReleased
        actualizarLista(txtBuscarComentario.getText()); 
    }//GEN-LAST:event_txtBuscarComentarioKeyReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        limpiarEntradas();
        this.pnlSliderRetro.setPanelNormal(pnlTablaRetro);
        btnVolver.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugerenciasActionPerformed
        if(!btnSugerencias.isSelected()){
            btnSugerencias.setSelected(true);
            btnReclamos.setSelected(false);
            this.tipo = "Sugerencia";
            actualizarLista("");
        }
       
    }//GEN-LAST:event_btnSugerenciasActionPerformed

    private void btnReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamosActionPerformed
        if(!btnReclamos.isSelected()){
            btnSugerencias.setSelected(false);
            btnReclamos.setSelected(true);
            this.tipo = "Reclamo";
            actualizarLista("");
        }
    }//GEN-LAST:event_btnReclamosActionPerformed

    private void btnVisualizarRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRetroActionPerformed

        int indice = tablaComentarios.getSelectedRow();        
        if(indice != -1)
        {
            Mensaje mensaje = listaRetro.get(indice);
            llenarDatos(mensaje);
            this.pnlSliderRetro.setPanelNormal(pnlVisualizar);
            btnVolver.setVisible(true);
        }
        else{     
            mensaje.cargarDatos("Visualizar Aviso"
                    ,"Seleccione un comentario de la lista.", 1);   
        }
    }//GEN-LAST:event_btnVisualizarRetroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnReclamos;
    private RSMaterialComponent.RSButtonMaterialIconOne btnSugerencias;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVisualizarRetro;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIDRetro;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblestado;
    private rojerusan.RSPanelEffect pnlSliderRetro;
    private javax.swing.JPanel pnlTablaRetro;
    private javax.swing.JPanel pnlVisualizar;
    private RSMaterialComponent.RSTableMetroCustom tablaComentarios;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscarComentario;
    private javax.swing.JTextArea txtcontenido;
    // End of variables declaration//GEN-END:variables
    public void actualizarLista(String buscar) {       
        try {
            listaRetro = new ArrayList<>();
            this.servicio.listarRetroAlimentacion(tablaComentarios,"",buscar
                    ,this.tipo,listaRetro,2);
        } catch (SQLException ex) {
            mensaje.cargarDatos("Error al actualizar lista"
                    ,"No es posible cargar los registros de la lista.", 1); 
        }
    }
    private void limpiarEntradas(){
        lblTipo.setText("");
        txtcontenido.setText("");      
        lblFecha.setVisible(true);
        lblFecha.setVisible(false);
      
    }
    private void llenarDatos(Mensaje mensaje) { 
        lblTipo.setText(mensaje.getTipo());
        lblIDRetro.setText(mensaje.getCod());
        lblIdUsuario.setText(mensaje.getNombreUsuario());
        txtcontenido.setText(mensaje.getContenido());      
        lblFecha.setText(mensaje.getFecha().toString());     
    }
    public void cargarServicio(ServiciosUsuario servicio){
        this.servicio = servicio;        
        tipo = "Sugerencia";   
        this.pnlSliderRetro.setPanelNormal(pnlTablaRetro);
        btnVolver.setVisible(false);
        actualizarLista("");
    }
}
