/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas.Trabajador;

import Entidades.*;
import InterfacesGraficas.Login.IniciarSesion;

/**
 *
 * @author HanselChavez
 */
public class PrincipalTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalTrabajador
     */
    Usuario user;
    IniciarSesion padre;
  
    public PrincipalTrabajador(Usuario user,IniciarSesion padre) {       
        initComponents();
        inciarValores(user, padre);      
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new newscomponents.RSButtonGradientIcon_new();
        btnUsuarios = new newscomponents.RSButtonGradientIcon_new();
        btnSolicitudes = new newscomponents.RSButtonGradientIcon_new();
        btnRetroalimentacion = new newscomponents.RSButtonGradientIcon_new();
        btnAvisos = new newscomponents.RSButtonGradientIcon_new();
        btnPerfil = new newscomponents.RSButtonGradientIcon_new();
        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lblFotoPrincipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlslider = new newscomponents.RSPanelEffect();
        pnlSolicitantes = new InterfacesGraficas.Trabajador.pnSolicitantes();
        pnlAvisosEnviados = new InterfacesGraficas.Trabajador.pnlAvisosEnviados();
        pnlComentarios = new InterfacesGraficas.Trabajador.pnlComentarios();
        pnlPerfil = new InterfacesGraficas.Perfil.pnlPerfiles();
        pnlSolicitudes = new InterfacesGraficas.Trabajador.pnlSolicitudes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 87, 151));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(12, 140, 233));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.VERTICAL);

        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnSalir.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnSalir.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnSalir.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(10);
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS_POWER);
        btnSalir.setSizeIcon(40.0F);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(12, 140, 233));
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnUsuarios.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnUsuarios.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnUsuarios.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(10);
        btnUsuarios.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        btnUsuarios.setSelected(true);
        btnUsuarios.setSizeIcon(40.0F);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnSolicitudes.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitudes.setText("SOLICITUDES");
        btnSolicitudes.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnSolicitudes.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnSolicitudes.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnSolicitudes.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnSolicitudes.setFocusPainted(false);
        btnSolicitudes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSolicitudes.setIconTextGap(10);
        btnSolicitudes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_BOOKS);
        btnSolicitudes.setSizeIcon(40.0F);
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        btnRetroalimentacion.setForeground(new java.awt.Color(0, 0, 0));
        btnRetroalimentacion.setText("RETROALIMENTACION");
        btnRetroalimentacion.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnRetroalimentacion.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnRetroalimentacion.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnRetroalimentacion.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnRetroalimentacion.setFocusPainted(false);
        btnRetroalimentacion.setFont(new java.awt.Font("Roboto Bold", 1, 13)); // NOI18N
        btnRetroalimentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetroalimentacion.setIconTextGap(10);
        btnRetroalimentacion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.COMMENT);
        btnRetroalimentacion.setSizeIcon(40.0F);
        btnRetroalimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroalimentacionActionPerformed(evt);
            }
        });

        btnAvisos.setForeground(new java.awt.Color(0, 0, 0));
        btnAvisos.setText("AVISOS");
        btnAvisos.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnAvisos.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnAvisos.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnAvisos.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnAvisos.setFocusPainted(false);
        btnAvisos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAvisos.setIconTextGap(10);
        btnAvisos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ANNOUNCEMENT);
        btnAvisos.setSizeIcon(40.0F);
        btnAvisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvisosActionPerformed(evt);
            }
        });

        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setText("PERFIL");
        btnPerfil.setColorPrimario(new java.awt.Color(0, 87, 151));
        btnPerfil.setColorPrimarioHover(new java.awt.Color(255, 153, 0));
        btnPerfil.setColorSecundario(new java.awt.Color(12, 140, 233));
        btnPerfil.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        btnPerfil.setFocusPainted(false);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(10);
        btnPerfil.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BOX);
        btnPerfil.setInheritsPopupMenu(true);
        btnPerfil.setSizeIcon(40.0F);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        lblnombres.setBackground(new java.awt.Color(255, 255, 255));
        lblnombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombres.setForeground(new java.awt.Color(255, 255, 255));
        lblnombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblapellidos.setBackground(new java.awt.Color(255, 255, 255));
        lblapellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblapellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblFotoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        lblFotoPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroalimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblnombres, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(lblapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addComponent(lblFotoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFotoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRetroalimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel2.setBackground(new java.awt.Color(12, 140, 233));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32wtminimize-sign.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32wtclose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addGap(8, 8, 8)
                .addComponent(btnClose)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimize)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        pnlslider.setBackground(new java.awt.Color(255, 255, 255));

        pnlSolicitantes.setName("pnlSolicitantes"); // NOI18N
        pnlslider.add(pnlSolicitantes, "card2");

        pnlAvisosEnviados.setName("pnlAvisosEnviados"); // NOI18N
        pnlslider.add(pnlAvisosEnviados, "card3");

        pnlComentarios.setName("pnlComentarios"); // NOI18N
        pnlslider.add(pnlComentarios, "card4");

        pnlPerfil.setName("pnlPerfil"); // NOI18N
        pnlslider.add(pnlPerfil, "card6");

        pnlSolicitudes.setName("pnlSolicitudes"); // NOI18N
        pnlslider.add(pnlSolicitudes, "card6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlslider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlslider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        cerrarForm();
    }//GEN-LAST:event_btnCloseMouseClicked
    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if(!btnUsuarios.isSelected()){    
            btnUsuarios.setSelected(true);
            btnSolicitudes.setSelected(false);
            btnRetroalimentacion.setSelected(false);
            btnAvisos.setSelected(false);
            btnPerfil.setSelected(false);            
            this.pnlslider.setPanelNormal(this.pnlSolicitantes);  
        }        
    }//GEN-LAST:event_btnUsuariosActionPerformed
    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        if(!btnSolicitudes.isSelected()){            
            btnUsuarios.setSelected(false);
            btnSolicitudes.setSelected(true);
            btnRetroalimentacion.setSelected(false);
            btnAvisos.setSelected(false);
            btnPerfil.setSelected(false);
            pnlSolicitudes.cargarServicio(this.padre.getServicioUsuario());
            this.pnlslider.setPanelNormal(this.pnlSolicitudes);            
        }        
    }//GEN-LAST:event_btnSolicitudesActionPerformed
    private void btnRetroalimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroalimentacionActionPerformed
        if(!btnRetroalimentacion.isSelected()){           
            btnUsuarios.setSelected(false);
            btnSolicitudes.setSelected(false);
            btnRetroalimentacion.setSelected(true);
            btnAvisos.setSelected(false);
            btnPerfil.setSelected(false);
            pnlComentarios.cargarServicio(this.padre.getServicioUsuario());            
            this.pnlslider.setPanelNormal(this.pnlComentarios);          
        }
    }//GEN-LAST:event_btnRetroalimentacionActionPerformed
    private void btnAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvisosActionPerformed
        if(!btnAvisos.isSelected()){            
            btnUsuarios.setSelected(false);
            btnSolicitudes.setSelected(false);
            btnRetroalimentacion.setSelected(false);
            btnAvisos.setSelected(true);
            btnPerfil.setSelected(false);
            pnlAvisosEnviados.cargarUsuario(user, padre.getServicioUsuario());           
            this.pnlslider.setPanelNormal(this.pnlAvisosEnviados);            
        }
    }//GEN-LAST:event_btnAvisosActionPerformed
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        if(!btnPerfil.isSelected()){           
            btnUsuarios.setSelected(false);
            btnSolicitudes.setSelected(false);
            btnRetroalimentacion.setSelected(false);
            btnAvisos.setSelected(false);
            btnPerfil.setSelected(true);
            pnlPerfil.cargarDatos(user, this,padre);                
            this.pnlslider.setPanelNormal(pnlPerfil);           
         }
    }//GEN-LAST:event_btnPerfilActionPerformed
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonGradientIcon_new btnAvisos;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private newscomponents.RSButtonGradientIcon_new btnPerfil;
    private newscomponents.RSButtonGradientIcon_new btnRetroalimentacion;
    private newscomponents.RSButtonGradientIcon_new btnSalir;
    private newscomponents.RSButtonGradientIcon_new btnSolicitudes;
    private newscomponents.RSButtonGradientIcon_new btnUsuarios;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFotoPrincipal;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblnombres;
    private InterfacesGraficas.Trabajador.pnlAvisosEnviados pnlAvisosEnviados;
    private InterfacesGraficas.Trabajador.pnlComentarios pnlComentarios;
    private InterfacesGraficas.Perfil.pnlPerfiles pnlPerfil;
    private InterfacesGraficas.Trabajador.pnSolicitantes pnlSolicitantes;
    private InterfacesGraficas.Trabajador.pnlSolicitudes pnlSolicitudes;
    private newscomponents.RSPanelEffect pnlslider;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    // End of variables declaration//GEN-END:variables
     public void inciarValores(Usuario user1, IniciarSesion padre1) {
        this.user = user1;
        this.padre = padre1;
        this.setLocationRelativeTo(null);
        lblnombres.setText(user.getNombres());
        lblapellidos.setText(user.getApellidos());    
        pnlSolicitantes.cargarServicio(padre1.getServicioUsuario());
        this.pnlslider.setPanelNormal(pnlSolicitantes);
    }
    
    private void cerrarForm() {
        System.exit(0);
    }
 
}
